"""add subdomain and brand_color to school

Revision ID: 9652898c5b8c
Revises: a810a0995cdf
Create Date: 2026-06-12 21:23:46.940001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9652898c5b8c'
down_revision: Union[str, None] = 'a810a0995cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('subdomain', sa.String(length=50), nullable=True))
    op.add_column('school', sa.Column('brand_color', sa.String(length=7), nullable=False))
    op.create_index(op.f('ix_school_subdomain'), 'school', ['subdomain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_subdomain'), table_name='school')
    op.drop_column('school', 'brand_color')
    op.drop_column('school', 'subdomain')
    # ### end Alembic commands ###
