"""add_unique_constraint_staff_number_per_school

Revision ID: 96b13ea00b18
Revises: d37ce793938b
Create Date: 2026-06-12 22:40:39.029059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b13ea00b18'
down_revision: Union[str, None] = 'd37ce793938b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_staff_member_school_number', 'staff_member', ['school_id', 'staff_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_staff_member_school_number', 'staff_member', type_='unique')
    # ### end Alembic commands ###
