"""phase1_baseline

Revision ID: a810a0995cdf
Revises: 
Create Date: 2026-06-11 22:21:57.407057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a810a0995cdf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ghana_public_holiday',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ghana_public_holiday_date'), 'ghana_public_holiday', ['date'], unique=False)
    op.create_table('ghana_region',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ghana_district',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['ghana_region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_ghana_district_region_id'), 'ghana_district', ['region_id'], unique=False)
    op.create_table('school',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('school_code', sa.String(length=20), nullable=False),
    sa.Column('school_type', sa.Enum('BASIC', 'SHS', name='schooltype'), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('motto', sa.String(length=200), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['ghana_district.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['ghana_region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_school_code'), 'school', ['school_code'], unique=True)
    op.create_table('academic_year',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_academic_year_school_name')
    )
    op.create_index(op.f('ix_academic_year_school_id'), 'academic_year', ['school_id'], unique=False)
    op.create_table('assessment_type',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_type_school_id'), 'assessment_type', ['school_id'], unique=False)
    op.create_table('fee_type',
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_type_school_id'), 'fee_type', ['school_id'], unique=False)
    op.create_table('grading_scale',
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grading_scale_school_id'), 'grading_scale', ['school_id'], unique=False)
    op.create_table('guardian',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardian_school_id'), 'guardian', ['school_id'], unique=False)
    op.create_table('house',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'MIXED', name='housegender'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_school_id'), 'house', ['school_id'], unique=False)
    op.create_table('school_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=2000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'key', name='uq_school_config_key')
    )
    op.create_index(op.f('ix_school_config_school_id'), 'school_config', ['school_id'], unique=False)
    op.create_table('school_period',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('day_of_week', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN', name='dayofweek'), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'day_of_week', 'period_number', name='uq_school_period')
    )
    op.create_index(op.f('ix_school_period_school_id'), 'school_period', ['school_id'], unique=False)
    op.create_table('school_schedule',
    sa.Column('day_of_week', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN', name='dayofweek'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_school_day', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'day_of_week', name='uq_school_schedule_day')
    )
    op.create_index(op.f('ix_school_schedule_school_id'), 'school_schedule', ['school_id'], unique=False)
    op.create_table('shs_programme',
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shs_programme_school_id'), 'shs_programme', ['school_id'], unique=False)
    op.create_table('sms_config',
    sa.Column('provider', sa.Enum('AFRICAS_TALKING', 'HUBTEL', 'ARKESEL', 'WIGAL', 'TWILIO', name='smsprovider'), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=False),
    sa.Column('api_secret', sa.String(length=500), nullable=True),
    sa.Column('sender_id', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_config_school_id'), 'sms_config', ['school_id'], unique=False)
    op.create_table('staff_position',
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_position_school_id'), 'staff_position', ['school_id'], unique=False)
    op.create_table('student',
    sa.Column('admission_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('hometown', sa.String(length=100), nullable=True),
    sa.Column('residential_address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'admission_number', name='uq_student_admission')
    )
    op.create_index(op.f('ix_student_admission_number'), 'student', ['admission_number'], unique=False)
    op.create_index(op.f('ix_student_school_id'), 'student', ['school_id'], unique=False)
    op.create_table('subject_catalogue',
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subject_type', sa.Enum('CORE', 'ELECTIVE', name='subjecttype'), nullable=False),
    sa.Column('level', sa.Enum('BASIC', 'SHS', name='schoollevel'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_catalogue_school_id'), 'subject_catalogue', ['school_id'], unique=False)
    op.create_table('academic_term',
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('term_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'academic_year_id', 'term_number', name='uq_term_year_number')
    )
    op.create_index(op.f('ix_academic_term_academic_year_id'), 'academic_term', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_academic_term_school_id'), 'academic_term', ['school_id'], unique=False)
    op.create_table('class',
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('year_group', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.UUID(), nullable=True),
    sa.Column('stream', sa.String(length=10), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programme_id'], ['shs_programme.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_academic_year_id'), 'class', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_class_school_id'), 'class', ['school_id'], unique=False)
    op.create_table('grade',
    sa.Column('grading_scale_id', sa.UUID(), nullable=False),
    sa.Column('min_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('letter_grade', sa.String(length=5), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('gpa_points', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('remarks', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['grading_scale_id'], ['grading_scale.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grading_scale_id', 'letter_grade', name='uq_grade_letter')
    )
    op.create_index(op.f('ix_grade_grading_scale_id'), 'grade', ['grading_scale_id'], unique=False)
    op.create_table('position_permission',
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['staff_position.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id', 'module', 'action', name='uq_position_permission')
    )
    op.create_index(op.f('ix_position_permission_position_id'), 'position_permission', ['position_id'], unique=False)
    op.create_table('room',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_house_id'), 'room', ['house_id'], unique=False)
    op.create_index(op.f('ix_room_school_id'), 'room', ['school_id'], unique=False)
    op.create_table('staff_member',
    sa.Column('staff_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=True),
    sa.Column('national_id', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['staff_position.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_member_school_id'), 'staff_member', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_member_staff_number'), 'staff_member', ['staff_number'], unique=False)
    op.create_table('student_enrollment',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_at', sa.Date(), nullable=False),
    sa.Column('enrollment_type', sa.Enum('NEW', 'TRANSFER', 'READMISSION', name='enrollmenttype'), nullable=False),
    sa.Column('transfer_from_school', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_enrollment_school_id'), 'student_enrollment', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_enrollment_student_id'), 'student_enrollment', ['student_id'], unique=False)
    op.create_table('student_guardian',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'guardian_id', name='uq_student_guardian')
    )
    op.create_index(op.f('ix_student_guardian_school_id'), 'student_guardian', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_guardian_student_id'), 'student_guardian', ['student_id'], unique=False)
    op.create_table('student_medical_record',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('chronic_conditions', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('emergency_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_student_medical_record_school_id'), 'student_medical_record', ['school_id'], unique=False)
    op.create_table('subject',
    sa.Column('catalogue_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['catalogue_id'], ['subject_catalogue.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_school_id'), 'subject', ['school_id'], unique=False)
    op.create_table('assessment',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('assessment_type_id', sa.UUID(), nullable=False),
    sa.Column('academic_term_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_term.id'], ),
    sa.ForeignKeyConstraint(['assessment_type_id'], ['assessment_type.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_class_id'), 'assessment', ['class_id'], unique=False)
    op.create_index(op.f('ix_assessment_school_id'), 'assessment', ['school_id'], unique=False)
    op.create_table('class_subject',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'subject_id', name='uq_class_subject')
    )
    op.create_index(op.f('ix_class_subject_class_id'), 'class_subject', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_subject_school_id'), 'class_subject', ['school_id'], unique=False)
    op.create_table('class_teacher',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('staff_member_id', sa.UUID(), nullable=False),
    sa.Column('academic_term_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_term.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'academic_term_id', name='uq_class_teacher_term')
    )
    op.create_index(op.f('ix_class_teacher_class_id'), 'class_teacher', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_teacher_school_id'), 'class_teacher', ['school_id'], unique=False)
    op.create_table('fee_structure',
    sa.Column('academic_term_id', sa.UUID(), nullable=False),
    sa.Column('fee_type_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('applies_to_level', sa.String(length=20), nullable=True),
    sa.Column('applies_to_programme_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_term.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['applies_to_programme_id'], ['shs_programme.id'], ),
    sa.ForeignKeyConstraint(['fee_type_id'], ['fee_type.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_structure_academic_term_id'), 'fee_structure', ['academic_term_id'], unique=False)
    op.create_index(op.f('ix_fee_structure_school_id'), 'fee_structure', ['school_id'], unique=False)
    op.create_table('house_master',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('staff_member_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_master_house_id'), 'house_master', ['house_id'], unique=False)
    op.create_index(op.f('ix_house_master_school_id'), 'house_master', ['school_id'], unique=False)
    op.create_table('school_calendar',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_type', sa.Enum('SCHOOL_DAY', 'PUBLIC_HOLIDAY', 'SCHOOL_HOLIDAY', 'HALF_DAY', 'WEEKEND', 'EXAM_DAY', name='daytype'), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('academic_term_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_term.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'date', name='uq_school_calendar_date')
    )
    op.create_index(op.f('ix_school_calendar_date'), 'school_calendar', ['date'], unique=False)
    op.create_index(op.f('ix_school_calendar_school_id'), 'school_calendar', ['school_id'], unique=False)
    op.create_table('staff_emergency_contact',
    sa.Column('staff_member_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_type', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_emergency_contact_school_id'), 'staff_emergency_contact', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_emergency_contact_staff_member_id'), 'staff_emergency_contact', ['staff_member_id'], unique=False)
    op.create_table('staff_permission',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('staff_member_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_member_id', 'module', 'action', name='uq_staff_permission')
    )
    op.create_index(op.f('ix_staff_permission_school_id'), 'staff_permission', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_permission_staff_member_id'), 'staff_permission', ['staff_member_id'], unique=False)
    op.create_table('staff_qualification',
    sa.Column('staff_member_id', sa.UUID(), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('qualification_type', sa.String(length=100), nullable=False),
    sa.Column('field_of_study', sa.String(length=200), nullable=True),
    sa.Column('year_obtained', sa.Integer(), nullable=True),
    sa.Column('certificate_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_qualification_school_id'), 'staff_qualification', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_qualification_staff_member_id'), 'staff_qualification', ['staff_member_id'], unique=False)
    op.create_table('student_fee_summary',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('academic_term_id', sa.UUID(), nullable=False),
    sa.Column('total_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_discounted', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_payment_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_term.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'academic_term_id', name='uq_fee_summary')
    )
    op.create_index(op.f('ix_student_fee_summary_school_id'), 'student_fee_summary', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_fee_summary_student_id'), 'student_fee_summary', ['student_id'], unique=False)
    op.create_table('student_house_assignment',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.Date(), nullable=False),
    sa.Column('vacated_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_house_assignment_school_id'), 'student_house_assignment', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_house_assignment_student_id'), 'student_house_assignment', ['student_id'], unique=False)
    op.create_table('subject_teacher',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('staff_member_id', sa.UUID(), nullable=False),
    sa.Column('academic_term_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_term.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'subject_id', 'academic_term_id', name='uq_subject_teacher_term')
    )
    op.create_index(op.f('ix_subject_teacher_class_id'), 'subject_teacher', ['class_id'], unique=False)
    op.create_index(op.f('ix_subject_teacher_school_id'), 'subject_teacher', ['school_id'], unique=False)
    op.create_table('user',
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('login_type', sa.Enum('EMAIL', 'PHONE', 'ADMISSION_ID', name='logintype'), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('admission_id', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('staff_member_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'admission_id', name='uq_user_school_admission')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_index(op.f('ix_user_school_id'), 'user', ['school_id'], unique=False)
    op.create_table('attendance_record',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('school_calendar_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendancestatus'), nullable=False),
    sa.Column('recorded_by_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['school_period.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_calendar_id'], ['school_calendar.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'school_calendar_id', 'period_id', name='uq_attendance_student_calendar_period')
    )
    op.create_index(op.f('ix_attendance_record_school_calendar_id'), 'attendance_record', ['school_calendar_id'], unique=False)
    op.create_index(op.f('ix_attendance_record_school_id'), 'attendance_record', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_record_student_id'), 'attendance_record', ['student_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_school_id'), 'audit_log', ['school_id'], unique=False)
    op.create_table('document_record',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_record_entity_id'), 'document_record', ['entity_id'], unique=False)
    op.create_index(op.f('ix_document_record_school_id'), 'document_record', ['school_id'], unique=False)
    op.create_table('exeat',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'RETURNED', name='exeatstatus'), nullable=False),
    sa.Column('actual_return_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exeat_school_id'), 'exeat', ['school_id'], unique=False)
    op.create_index(op.f('ix_exeat_student_id'), 'exeat', ['student_id'], unique=False)
    op.create_table('graduation_record',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('graduation_type', sa.Enum('PROMOTED', 'GRADUATED', 'REPEATED', 'WITHDRAWN', 'TRANSFERRED', name='graduationtype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graduation_record_school_id'), 'graduation_record', ['school_id'], unique=False)
    op.create_index(op.f('ix_graduation_record_student_id'), 'graduation_record', ['student_id'], unique=False)
    op.create_table('import_batch',
    sa.Column('import_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL', name='importstatus'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('initiated_by_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batch_school_id'), 'import_batch', ['school_id'], unique=False)
    op.create_table('night_roll_call',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('school_calendar_id', sa.UUID(), nullable=False),
    sa.Column('recorded_by_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_expected', sa.Integer(), nullable=False),
    sa.Column('total_present', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_calendar_id'], ['school_calendar.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_night_roll_call_house_id'), 'night_roll_call', ['house_id'], unique=False)
    op.create_index(op.f('ix_night_roll_call_school_calendar_id'), 'night_roll_call', ['school_calendar_id'], unique=False)
    op.create_index(op.f('ix_night_roll_call_school_id'), 'night_roll_call', ['school_id'], unique=False)
    op.create_table('offline_sync_conflict',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('outbox_id', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('client_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('server_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conflict_type', sa.String(length=50), nullable=False),
    sa.Column('resolution', sa.Enum('CLIENT_WINS', 'SERVER_WINS', 'MERGED', 'DISCARDED', name='conflictresolution'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offline_sync_conflict_school_id'), 'offline_sync_conflict', ['school_id'], unique=False)
    op.create_index(op.f('ix_offline_sync_conflict_user_id'), 'offline_sync_conflict', ['user_id'], unique=False)
    op.create_table('score',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('raw_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('cached_grade_label', sa.String(length=10), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('entered_by_id', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entered_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'student_id', name='uq_score_assessment_student')
    )
    op.create_index(op.f('ix_score_assessment_id'), 'score', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_score_school_id'), 'score', ['school_id'], unique=False)
    op.create_index(op.f('ix_score_student_id'), 'score', ['student_id'], unique=False)
    op.create_table('staff_leave',
    sa.Column('staff_member_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days_count', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus'), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_leave_school_id'), 'staff_leave', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_leave_staff_member_id'), 'staff_leave', ['staff_member_id'], unique=False)
    op.create_table('staff_promotion',
    sa.Column('staff_member_id', sa.UUID(), nullable=False),
    sa.Column('from_position_id', sa.UUID(), nullable=True),
    sa.Column('to_position_id', sa.UUID(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['from_position_id'], ['staff_position.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_position_id'], ['staff_position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_promotion_school_id'), 'staff_promotion', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_promotion_staff_member_id'), 'staff_promotion', ['staff_member_id'], unique=False)
    op.create_table('student_behaviour_record',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('academic_term_id', sa.UUID(), nullable=False),
    sa.Column('incident_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_term.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_behaviour_record_school_id'), 'student_behaviour_record', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_behaviour_record_student_id'), 'student_behaviour_record', ['student_id'], unique=False)
    op.create_table('student_fee_record',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('academic_term_id', sa.UUID(), nullable=False),
    sa.Column('fee_structure_id', sa.UUID(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_waived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_term.id'], ),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structure.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'fee_structure_id', name='uq_student_fee_record')
    )
    op.create_index(op.f('ix_student_fee_record_school_id'), 'student_fee_record', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_fee_record_student_id'), 'student_fee_record', ['student_id'], unique=False)
    op.create_table('term_enrollment',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('academic_term_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_by_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_term.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['enrolled_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'academic_term_id', name='uq_term_enrollment')
    )
    op.create_index(op.f('ix_term_enrollment_class_id'), 'term_enrollment', ['class_id'], unique=False)
    op.create_index(op.f('ix_term_enrollment_school_id'), 'term_enrollment', ['school_id'], unique=False)
    op.create_index(op.f('ix_term_enrollment_student_id'), 'term_enrollment', ['student_id'], unique=False)
    op.create_table('transfer_request',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('requesting_school_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='transferstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['requesting_school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_request_school_id'), 'transfer_request', ['school_id'], unique=False)
    op.create_index(op.f('ix_transfer_request_student_id'), 'transfer_request', ['student_id'], unique=False)
    op.create_table('user_invitation',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['staff_position.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_user_invitation_school_id'), 'user_invitation', ['school_id'], unique=False)
    op.create_table('user_session',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=200), nullable=False),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index(op.f('ix_user_session_expires_at'), 'user_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_session_user_id'), 'user_session', ['user_id'], unique=False)
    op.create_table('fee_discount',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('academic_term_id', sa.UUID(), nullable=False),
    sa.Column('fee_record_id', sa.UUID(), nullable=False),
    sa.Column('discount_type', sa.Enum('SCHOLARSHIP', 'BURSARY', 'SIBLING', 'STAFF_WARD', 'OTHER', name='discounttype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_term.id'], ),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fee_record_id'], ['student_fee_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_discount_school_id'), 'fee_discount', ['school_id'], unique=False)
    op.create_index(op.f('ix_fee_discount_student_id'), 'fee_discount', ['student_id'], unique=False)
    op.create_table('fee_instalment_plan',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('fee_record_id', sa.UUID(), nullable=False),
    sa.Column('instalment_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fee_record_id'], ['student_fee_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_instalment_plan_school_id'), 'fee_instalment_plan', ['school_id'], unique=False)
    op.create_index(op.f('ix_fee_instalment_plan_student_id'), 'fee_instalment_plan', ['student_id'], unique=False)
    op.create_table('fee_payment',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('academic_term_id', sa.UUID(), nullable=False),
    sa.Column('fee_record_id', sa.UUID(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'MOBILE_MONEY', 'BANK_TRANSFER', 'CHEQUE', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('received_by_id', sa.UUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['academic_term_id'], ['academic_term.id'], ),
    sa.ForeignKeyConstraint(['fee_record_id'], ['student_fee_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_payment_fee_record_id'), 'fee_payment', ['fee_record_id'], unique=False)
    op.create_index(op.f('ix_fee_payment_payment_date'), 'fee_payment', ['payment_date'], unique=False)
    op.create_index(op.f('ix_fee_payment_school_id'), 'fee_payment', ['school_id'], unique=False)
    op.create_index(op.f('ix_fee_payment_student_id'), 'fee_payment', ['student_id'], unique=False)
    op.create_table('import_row',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_row_batch_id'), 'import_row', ['batch_id'], unique=False)
    op.create_index(op.f('ix_import_row_school_id'), 'import_row', ['school_id'], unique=False)
    op.create_table('score_audit_log',
    sa.Column('score_id', sa.UUID(), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=False),
    sa.Column('old_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('new_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['score_id'], ['score.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_audit_log_school_id'), 'score_audit_log', ['school_id'], unique=False)
    op.create_index(op.f('ix_score_audit_log_score_id'), 'score_audit_log', ['score_id'], unique=False)
    op.create_table('subject_registration',
    sa.Column('term_enrollment_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('registration_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['term_enrollment_id'], ['term_enrollment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_enrollment_id', 'subject_id', name='uq_subject_registration')
    )
    op.create_index(op.f('ix_subject_registration_school_id'), 'subject_registration', ['school_id'], unique=False)
    op.create_index(op.f('ix_subject_registration_term_enrollment_id'), 'subject_registration', ['term_enrollment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_registration_term_enrollment_id'), table_name='subject_registration')
    op.drop_index(op.f('ix_subject_registration_school_id'), table_name='subject_registration')
    op.drop_table('subject_registration')
    op.drop_index(op.f('ix_score_audit_log_score_id'), table_name='score_audit_log')
    op.drop_index(op.f('ix_score_audit_log_school_id'), table_name='score_audit_log')
    op.drop_table('score_audit_log')
    op.drop_index(op.f('ix_import_row_school_id'), table_name='import_row')
    op.drop_index(op.f('ix_import_row_batch_id'), table_name='import_row')
    op.drop_table('import_row')
    op.drop_index(op.f('ix_fee_payment_student_id'), table_name='fee_payment')
    op.drop_index(op.f('ix_fee_payment_school_id'), table_name='fee_payment')
    op.drop_index(op.f('ix_fee_payment_payment_date'), table_name='fee_payment')
    op.drop_index(op.f('ix_fee_payment_fee_record_id'), table_name='fee_payment')
    op.drop_table('fee_payment')
    op.drop_index(op.f('ix_fee_instalment_plan_student_id'), table_name='fee_instalment_plan')
    op.drop_index(op.f('ix_fee_instalment_plan_school_id'), table_name='fee_instalment_plan')
    op.drop_table('fee_instalment_plan')
    op.drop_index(op.f('ix_fee_discount_student_id'), table_name='fee_discount')
    op.drop_index(op.f('ix_fee_discount_school_id'), table_name='fee_discount')
    op.drop_table('fee_discount')
    op.drop_index(op.f('ix_user_session_user_id'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_expires_at'), table_name='user_session')
    op.drop_table('user_session')
    op.drop_index(op.f('ix_user_invitation_school_id'), table_name='user_invitation')
    op.drop_table('user_invitation')
    op.drop_index(op.f('ix_transfer_request_student_id'), table_name='transfer_request')
    op.drop_index(op.f('ix_transfer_request_school_id'), table_name='transfer_request')
    op.drop_table('transfer_request')
    op.drop_index(op.f('ix_term_enrollment_student_id'), table_name='term_enrollment')
    op.drop_index(op.f('ix_term_enrollment_school_id'), table_name='term_enrollment')
    op.drop_index(op.f('ix_term_enrollment_class_id'), table_name='term_enrollment')
    op.drop_table('term_enrollment')
    op.drop_index(op.f('ix_student_fee_record_student_id'), table_name='student_fee_record')
    op.drop_index(op.f('ix_student_fee_record_school_id'), table_name='student_fee_record')
    op.drop_table('student_fee_record')
    op.drop_index(op.f('ix_student_behaviour_record_student_id'), table_name='student_behaviour_record')
    op.drop_index(op.f('ix_student_behaviour_record_school_id'), table_name='student_behaviour_record')
    op.drop_table('student_behaviour_record')
    op.drop_index(op.f('ix_staff_promotion_staff_member_id'), table_name='staff_promotion')
    op.drop_index(op.f('ix_staff_promotion_school_id'), table_name='staff_promotion')
    op.drop_table('staff_promotion')
    op.drop_index(op.f('ix_staff_leave_staff_member_id'), table_name='staff_leave')
    op.drop_index(op.f('ix_staff_leave_school_id'), table_name='staff_leave')
    op.drop_table('staff_leave')
    op.drop_index(op.f('ix_score_student_id'), table_name='score')
    op.drop_index(op.f('ix_score_school_id'), table_name='score')
    op.drop_index(op.f('ix_score_assessment_id'), table_name='score')
    op.drop_table('score')
    op.drop_index(op.f('ix_offline_sync_conflict_user_id'), table_name='offline_sync_conflict')
    op.drop_index(op.f('ix_offline_sync_conflict_school_id'), table_name='offline_sync_conflict')
    op.drop_table('offline_sync_conflict')
    op.drop_index(op.f('ix_night_roll_call_school_id'), table_name='night_roll_call')
    op.drop_index(op.f('ix_night_roll_call_school_calendar_id'), table_name='night_roll_call')
    op.drop_index(op.f('ix_night_roll_call_house_id'), table_name='night_roll_call')
    op.drop_table('night_roll_call')
    op.drop_index(op.f('ix_import_batch_school_id'), table_name='import_batch')
    op.drop_table('import_batch')
    op.drop_index(op.f('ix_graduation_record_student_id'), table_name='graduation_record')
    op.drop_index(op.f('ix_graduation_record_school_id'), table_name='graduation_record')
    op.drop_table('graduation_record')
    op.drop_index(op.f('ix_exeat_student_id'), table_name='exeat')
    op.drop_index(op.f('ix_exeat_school_id'), table_name='exeat')
    op.drop_table('exeat')
    op.drop_index(op.f('ix_document_record_school_id'), table_name='document_record')
    op.drop_index(op.f('ix_document_record_entity_id'), table_name='document_record')
    op.drop_table('document_record')
    op.drop_index(op.f('ix_audit_log_school_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_attendance_record_student_id'), table_name='attendance_record')
    op.drop_index(op.f('ix_attendance_record_school_id'), table_name='attendance_record')
    op.drop_index(op.f('ix_attendance_record_school_calendar_id'), table_name='attendance_record')
    op.drop_table('attendance_record')
    op.drop_index(op.f('ix_user_school_id'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_subject_teacher_school_id'), table_name='subject_teacher')
    op.drop_index(op.f('ix_subject_teacher_class_id'), table_name='subject_teacher')
    op.drop_table('subject_teacher')
    op.drop_index(op.f('ix_student_house_assignment_student_id'), table_name='student_house_assignment')
    op.drop_index(op.f('ix_student_house_assignment_school_id'), table_name='student_house_assignment')
    op.drop_table('student_house_assignment')
    op.drop_index(op.f('ix_student_fee_summary_student_id'), table_name='student_fee_summary')
    op.drop_index(op.f('ix_student_fee_summary_school_id'), table_name='student_fee_summary')
    op.drop_table('student_fee_summary')
    op.drop_index(op.f('ix_staff_qualification_staff_member_id'), table_name='staff_qualification')
    op.drop_index(op.f('ix_staff_qualification_school_id'), table_name='staff_qualification')
    op.drop_table('staff_qualification')
    op.drop_index(op.f('ix_staff_permission_staff_member_id'), table_name='staff_permission')
    op.drop_index(op.f('ix_staff_permission_school_id'), table_name='staff_permission')
    op.drop_table('staff_permission')
    op.drop_index(op.f('ix_staff_emergency_contact_staff_member_id'), table_name='staff_emergency_contact')
    op.drop_index(op.f('ix_staff_emergency_contact_school_id'), table_name='staff_emergency_contact')
    op.drop_table('staff_emergency_contact')
    op.drop_index(op.f('ix_school_calendar_school_id'), table_name='school_calendar')
    op.drop_index(op.f('ix_school_calendar_date'), table_name='school_calendar')
    op.drop_table('school_calendar')
    op.drop_index(op.f('ix_house_master_school_id'), table_name='house_master')
    op.drop_index(op.f('ix_house_master_house_id'), table_name='house_master')
    op.drop_table('house_master')
    op.drop_index(op.f('ix_fee_structure_school_id'), table_name='fee_structure')
    op.drop_index(op.f('ix_fee_structure_academic_term_id'), table_name='fee_structure')
    op.drop_table('fee_structure')
    op.drop_index(op.f('ix_class_teacher_school_id'), table_name='class_teacher')
    op.drop_index(op.f('ix_class_teacher_class_id'), table_name='class_teacher')
    op.drop_table('class_teacher')
    op.drop_index(op.f('ix_class_subject_school_id'), table_name='class_subject')
    op.drop_index(op.f('ix_class_subject_class_id'), table_name='class_subject')
    op.drop_table('class_subject')
    op.drop_index(op.f('ix_assessment_school_id'), table_name='assessment')
    op.drop_index(op.f('ix_assessment_class_id'), table_name='assessment')
    op.drop_table('assessment')
    op.drop_index(op.f('ix_subject_school_id'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_student_medical_record_school_id'), table_name='student_medical_record')
    op.drop_table('student_medical_record')
    op.drop_index(op.f('ix_student_guardian_student_id'), table_name='student_guardian')
    op.drop_index(op.f('ix_student_guardian_school_id'), table_name='student_guardian')
    op.drop_table('student_guardian')
    op.drop_index(op.f('ix_student_enrollment_student_id'), table_name='student_enrollment')
    op.drop_index(op.f('ix_student_enrollment_school_id'), table_name='student_enrollment')
    op.drop_table('student_enrollment')
    op.drop_index(op.f('ix_staff_member_staff_number'), table_name='staff_member')
    op.drop_index(op.f('ix_staff_member_school_id'), table_name='staff_member')
    op.drop_table('staff_member')
    op.drop_index(op.f('ix_room_school_id'), table_name='room')
    op.drop_index(op.f('ix_room_house_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_position_permission_position_id'), table_name='position_permission')
    op.drop_table('position_permission')
    op.drop_index(op.f('ix_grade_grading_scale_id'), table_name='grade')
    op.drop_table('grade')
    op.drop_index(op.f('ix_class_school_id'), table_name='class')
    op.drop_index(op.f('ix_class_academic_year_id'), table_name='class')
    op.drop_table('class')
    op.drop_index(op.f('ix_academic_term_school_id'), table_name='academic_term')
    op.drop_index(op.f('ix_academic_term_academic_year_id'), table_name='academic_term')
    op.drop_table('academic_term')
    op.drop_index(op.f('ix_subject_catalogue_school_id'), table_name='subject_catalogue')
    op.drop_table('subject_catalogue')
    op.drop_index(op.f('ix_student_school_id'), table_name='student')
    op.drop_index(op.f('ix_student_admission_number'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_staff_position_school_id'), table_name='staff_position')
    op.drop_table('staff_position')
    op.drop_index(op.f('ix_sms_config_school_id'), table_name='sms_config')
    op.drop_table('sms_config')
    op.drop_index(op.f('ix_shs_programme_school_id'), table_name='shs_programme')
    op.drop_table('shs_programme')
    op.drop_index(op.f('ix_school_schedule_school_id'), table_name='school_schedule')
    op.drop_table('school_schedule')
    op.drop_index(op.f('ix_school_period_school_id'), table_name='school_period')
    op.drop_table('school_period')
    op.drop_index(op.f('ix_school_config_school_id'), table_name='school_config')
    op.drop_table('school_config')
    op.drop_index(op.f('ix_house_school_id'), table_name='house')
    op.drop_table('house')
    op.drop_index(op.f('ix_guardian_school_id'), table_name='guardian')
    op.drop_table('guardian')
    op.drop_index(op.f('ix_grading_scale_school_id'), table_name='grading_scale')
    op.drop_table('grading_scale')
    op.drop_index(op.f('ix_fee_type_school_id'), table_name='fee_type')
    op.drop_table('fee_type')
    op.drop_index(op.f('ix_assessment_type_school_id'), table_name='assessment_type')
    op.drop_table('assessment_type')
    op.drop_index(op.f('ix_academic_year_school_id'), table_name='academic_year')
    op.drop_table('academic_year')
    op.drop_index(op.f('ix_school_school_code'), table_name='school')
    op.drop_table('school')
    op.drop_index(op.f('ix_ghana_district_region_id'), table_name='ghana_district')
    op.drop_table('ghana_district')
    op.drop_table('ghana_region')
    op.drop_index(op.f('ix_ghana_public_holiday_date'), table_name='ghana_public_holiday')
    op.drop_table('ghana_public_holiday')
    # ### end Alembic commands ###
