"""add_staff_member_id_to_user_invitation

Revision ID: d37ce793938b
Revises: 9652898c5b8c
Create Date: 2026-06-12 22:31:52.573403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37ce793938b'
down_revision: Union[str, None] = '9652898c5b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_invitation', sa.Column('staff_member_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user_invitation', 'staff_member', ['staff_member_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_invitation', type_='foreignkey')
    op.drop_column('user_invitation', 'staff_member_id')
    # ### end Alembic commands ###
