from __future__ import annotations

import re
import uuid
from datetime import datetime

from pydantic import BaseModel, EmailStr, field_validator

from app.models.school import EmailProvider, EmailStatus, SchoolOwnership, SchoolType, SmsProvider

_HEX_RE = re.compile(r"^#[0-9a-fA-F]{6}$")
_SUBDOMAIN_RE = re.compile(r"^[a-z0-9][a-z0-9-]{1,48}[a-z0-9]$")
_DOMAIN_RE = re.compile(r"^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$")


class SchoolCreate(BaseModel):
    name: str
    short_name: str | None = None
    school_code: str
    school_type: SchoolType
    region_id: uuid.UUID
    district_id: uuid.UUID
    phone: str | None = None
    email: EmailStr | None = None
    address: str | None = None
    motto: str | None = None
    established_year: int | None = None
    subdomain: str | None = None
    custom_domain: str | None = None
    brand_color: str = "#1e40af"
    has_boarding: bool = False

    @field_validator("school_code")
    @classmethod
    def code_uppercase(cls, v: str) -> str:
        return v.strip().upper()

    @field_validator("subdomain")
    @classmethod
    def subdomain_valid(cls, v: str | None) -> str | None:
        if v is None:
            return v
        v = v.lower().strip()
        if not _SUBDOMAIN_RE.match(v):
            raise ValueError("subdomain must be 3-50 lowercase letters, numbers, or hyphens")
        return v

    @field_validator("custom_domain")
    @classmethod
    def custom_domain_valid(cls, v: str | None) -> str | None:
        if v is None:
            return v
        v = v.lower().strip()
        if not _DOMAIN_RE.match(v):
            raise ValueError("custom_domain must be a valid fully-qualified domain name")
        return v

    @field_validator("brand_color")
    @classmethod
    def color_valid(cls, v: str) -> str:
        if not _HEX_RE.match(v):
            raise ValueError("brand_color must be a 6-digit hex colour, e.g. #1e40af")
        return v.lower()


class SchoolUpdate(BaseModel):
    name: str | None = None
    short_name: str | None = None
    phone: str | None = None
    email: EmailStr | None = None
    address: str | None = None
    motto: str | None = None
    established_year: int | None = None
    is_active: bool | None = None
    has_boarding: bool | None = None
    subdomain: str | None = None
    custom_domain: str | None = None
    brand_color: str | None = None

    @field_validator("subdomain")
    @classmethod
    def subdomain_valid(cls, v: str | None) -> str | None:
        if v is None:
            return v
        v = v.lower().strip()
        if not _SUBDOMAIN_RE.match(v):
            raise ValueError("subdomain must be 3-50 lowercase letters, numbers, or hyphens")
        return v

    @field_validator("custom_domain")
    @classmethod
    def custom_domain_valid(cls, v: str | None) -> str | None:
        if v is None:
            return v
        v = v.lower().strip()
        if not _DOMAIN_RE.match(v):
            raise ValueError("custom_domain must be a valid fully-qualified domain name")
        return v

    @field_validator("brand_color")
    @classmethod
    def color_valid(cls, v: str | None) -> str | None:
        if v is None:
            return v
        if not _HEX_RE.match(v):
            raise ValueError("brand_color must be a 6-digit hex colour, e.g. #1e40af")
        return v.lower()


class RegionRead(BaseModel):
    id: uuid.UUID
    name: str
    code: str

    model_config = {"from_attributes": True}


class DistrictRead(BaseModel):
    id: uuid.UUID
    name: str
    code: str
    region_id: uuid.UUID

    model_config = {"from_attributes": True}


class SchoolRead(BaseModel):
    id: uuid.UUID
    name: str
    short_name: str | None
    school_code: str
    school_type: SchoolType
    ownership: SchoolOwnership
    region_id: uuid.UUID
    district_id: uuid.UUID
    phone: str | None
    email: str | None
    address: str | None
    motto: str | None
    logo_path: str | None
    established_year: int | None
    is_active: bool
    has_boarding: bool
    subdomain: str | None
    custom_domain: str | None
    brand_color: str

    model_config = {"from_attributes": True}


class SchoolBranding(BaseModel):
    """
    Public branding data returned by GET /schools/public/{subdomain}.

    No auth required.  Contains only what the login screen needs — no
    internal IDs, contact details, or sensitive config.

    school_code is included because ADMISSION_ID login requires the GES code
    (e.g. "PRESEC"), which may differ from the URL subdomain slug ("presec-gh").

    LIGHT / DARK MODE
    -----------------
    brand_color is the single hex colour the school admin chose.
    The frontend derives the full palette from it:
      - Light mode base: warm off-white #f8f7f4 (not glaring white)
      - Dark mode base:  deep charcoal  #111318 (not pure black)
      - Tints/shades of brand_color auto-generated by the color utility
      - Foreground (white vs black) chosen by luminance contrast ratio
    Admins cannot break the UI — they only control brand_color.
    """
    school_name: str
    short_name: str | None
    school_type: SchoolType
    motto: str | None
    logo_url: str | None   # absolute URL, ready for <img src>
    brand_color: str
    school_code: str

    model_config = {"from_attributes": True}


class SchoolByDomainResult(SchoolBranding):
    """
    Returned by GET /schools/by-domain when a school is found for a custom domain.

    Extends SchoolBranding with the subdomain slug so the frontend can store
    the school identity consistently regardless of how it was reached.
    """
    subdomain: str | None = None


class SchoolConfigSet(BaseModel):
    key: str
    value: str


class SmsConfigCreate(BaseModel):
    provider: SmsProvider
    api_key: str
    api_secret: str | None = None
    sender_id: str


class SmsConfigRead(BaseModel):
    id: uuid.UUID
    provider: SmsProvider
    sender_id: str
    is_active: bool

    model_config = {"from_attributes": True}


class EmailConfigCreate(BaseModel):
    provider: EmailProvider
    host: str | None = None
    port: int | None = None
    username: str
    password: str | None = None
    from_name: str
    from_address: EmailStr
    use_tls: bool = True

    @field_validator("host")
    @classmethod
    def host_required_for_smtp(cls, v: str | None, info) -> str | None:
        return v

    def model_post_init(self, __context) -> None:
        if self.provider == EmailProvider.SMTP and not self.host:
            raise ValueError("host is required for SMTP provider")


class EmailConfigRead(BaseModel):
    id: uuid.UUID
    provider: EmailProvider
    host: str | None
    port: int | None
    from_name: str
    from_address: str
    use_tls: bool
    is_active: bool

    model_config = {"from_attributes": True}


class EmailActivateRequest(BaseModel):
    config_id: uuid.UUID


class EmailLogRead(BaseModel):
    id: uuid.UUID
    provider: EmailProvider
    recipient: str
    subject: str
    status: EmailStatus
    error_message: str | None
    entity_type: str | None
    entity_id: uuid.UUID | None
    sent_at: datetime

    model_config = {"from_attributes": True}

    model_config = {"from_attributes": True}
